test_stream_1 = "mjqjpqmgbljsphdztnvjfqwrcgsmlb"
test_stream_2 = "bvwbjplbgvbhsrlpgdmjqwftvncz"
test_stream_3 = "nppdvjthqldpwncqszvftbrmjlhg"
test_stream_4 = "nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"
test_stream_5 = "zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"